### Import Libraries

In [1]:
pip install scipy

Requirement already satisfied: scipy in c:\users\aksha\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (1.11.4)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy<1.28.0,>=1.21.6 in c:\users\aksha\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from scipy) (1.26.2)

In [2]:
import pandas as pd
import  pickle
import numpy as np
from scipy.stats import halfnorm

In [3]:
with open("ProfileData_pickleFiles/profile_data.pkl",'rb') as fp:
    df = pickle.load(fp)

In [4]:
df

,Bios,Movies,TV,Religion,Music,Sports,Travelling,Foodie,Books,Politics,Finance,Coding
0,Evil beer aficionado. Freelance introvert. Tv ...,4,5,1,1,5,0,6,2,0,5,5
1,Passionate gamer. Evil internet aficionado. St...,5,3,5,0,5,6,3,1,2,4,7
2,Social media guru. Tv expert. Amateur beer eva...,0,3,2,5,1,7,0,4,0,7,9
3,Reader. Incurable analyst. Proud pop culture e...,4,3,7,2,1,3,1,5,9,4,5
4,Typical gamer. Friend of animals everywhere. A...,2,9,1,2,6,9,3,4,5,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...
745,Social media fanatic. Typical coffee buff. Fre...,7,9,2,7,6,7,5,1,8,9,6
746,Student. Reader. Bacon trailblazer. Explorer. ...,8,6,7,6,5,0,6,6,0,8,0
747,Reader. Tv lover. Beer nerd. Incurable interne...,9,2,3,4,4,5,3,6,3,8,4
748,Amateur travel expert. Organizer. Alcohol fana...,9,0,2,1,0,9,3,0,2,8,3
749,Troublemaker. Food evangelist. Freelance inter...,4,7,0,9,0,6,8,4,6,7,6

In [5]:
# Using only Bios
# Removing the numerical data
df = df[['Bios']]

In [6]:
df

                                                  Bios
0    Evil beer aficionado. Freelance introvert. Tv ...
1    Passionate gamer. Evil internet aficionado. St...
2    Social media guru. Tv expert. Amateur beer eva...
3    Reader. Incurable analyst. Proud pop culture e...
4    Typical gamer. Friend of animals everywhere. A...
..                                                 ...
745  Social media fanatic. Typical coffee buff. Fre...
746  Student. Reader. Bacon trailblazer. Explorer. ...
747  Reader. Tv lover. Beer nerd. Incurable interne...
748  Amateur travel expert. Organizer. Alcohol fana...
749  Troublemaker. Food evangelist. Freelance inter...

[750 rows x 1 columns]

### Creating Lists for the Categories
Here, we are specifying the categories into subcategories and allocating the probability of being an interest to each subcategory of interest

In [7]:
#Probability distribution
p = {}

# TV Genres
tv = ['Comedy',
      'Drama',
      'Action/Adventure',
      'Suspense/Thriller',
      'Documentaries',
      'Crime/Mystery',
      'News',
      'SciFi',
      'History']

p['TV'] = [0.25,
           0.21,
           0.17,
           0.16,
           0.09,
           0.08,
           0.03,
           0.02,
           0.01]

# Movie Genres
movies = ['Adventure',
          'Action',
          'Drama',
          'Comedy',
          'Thriller',
          'Horror',
          'RomCom',
          'Musical',
          'Documentary']

p['Movies'] = [0.26,
               0.21,
               0.16,
               0.14,
               0.09,
               0.06,
               0.04,
               0.01, 
               0.03]

# Religions (could potentially create a spectrum)
religion = ['Catholic',
            'Christian',
            'Jewish',
            'Muslim',
            'Hindu',
            'Buddhist',
            'Spiritual',
            'Other',
            'Agnostic',
            'Atheist']

p['Religion'] = [0.07,
                 0.13,
                 0.01,
                 0.19,
                 0.24,
                 0.05,
                 0.10,
                 0.09,
                 0.07,
                 0.05]

# Music
music = ['Rock',
         'HipHop',
         'Romantic',
         'Pop',
         'Country',
         'EDM',
         'Jazz',
         'Classical',
         ]

p['Music'] = [0.25,
              0.19,
              0.16,
              0.14,
              0.10,
              0.06,
              0.04,
              0.03,
              0.02,
              0.01,]

# Sports
sports = [
          'Cricket',
          'Chess',
          'Badminton'
          'Football',
          'Baseball',
          'Basketball',
          'Hockey',
          'Soccer',
          'Other']

p['Sports'] = [0.29,
               0.24,
               0.23, 
               0.13,
               0.04,
               0.03,
               0.02,
               0.02]

# Politics (could also put on a spectrum)
politics = ['Liberal',
            'Progressive',
            'Centrist',
            'Moderate',
            'Conservative']

p['Politics'] = [0.26,
                 0.11,
                 0.11,
                 0.15,
                 0.37]

# Social Media
social = ['Facebook',
          'Youtube',
          'Twitter',
          'Reddit',
          'Instagram',
          'Pinterest',
          'LinkedIn',
          'SnapChat',
          'TikTok']

p['Social Media'] = [0.36,
                     0.27,
                     0.11,
                     0.09,
                     0.05,
                     0.03,
                     0.03,
                     0.03,
                     0.03]

# Programming
programming = [
          'Python',
          'Java',
          'JavaScript',
          'C++',
          'C#',
          'Swift',
          'Go'
         ]

p['programming'] = [
                    0.23,
                    0.20,
                    0.18,
                    0.15,
                    0.12,
                    0.10,
                    0.02
                   ]

#travelling
travelling = [
            'Treking',
            'Adventure',
            'Long Trips',
            'Short journeys'
             ]

p['travelling'] = [
                 0.35,
                 0.33,
                 0.21,
                 0.11
                  ]


# Age (generating random numbers based on half normal distribution)
age = halfnorm.rvs(loc=18,scale=8, size=df.shape[0]).astype(int)

# Lists of Names and the list of the lists
categories = [movies, religion, music, politics, social, sports,programming, travelling, age]

names = ['Movies','Religion', 'Music', 'Politics', 'Social Media', 'Sports', 'Programming', 'Traveller', 'Age']

combined = dict(zip(names, categories))

In [8]:
combined

{'Movies': ['Adventure',
  'Action',
  'Drama',
  'Comedy',
  'Thriller',
  'Horror',
  'RomCom',
  'Musical',
  'Documentary'],
 'Religion': ['Catholic',
  'Christian',
  'Jewish',
  'Muslim',
  'Hindu',
  'Buddhist',
  'Spiritual',
  'Other',
  'Agnostic',
  'Atheist'],
 'Music': ['Rock',
  'HipHop',
  'Romantic',
  'Pop',
  'Country',
  'EDM',
  'Jazz',
  'Classical'],
 'Politics': ['Liberal',
  'Progressive',
  'Centrist',
  'Moderate',
  'Conservative'],
 'Social Media': ['Facebook',
  'Youtube',
  'Twitter',
  'Reddit',
  'Instagram',
  'Pinterest',
  'LinkedIn',
  'SnapChat',
  'TikTok'],
 'Sports': ['Cricket',
  'Chess',
  'BadmintonFootball',
  'Baseball',
  'Basketball',
  'Hockey',
  'Soccer',
  'Other'],
 'Programming': ['Python', 'Java', 'JavaScript', 'C++', 'C#', 'Swift', 'Go'],
 'Traveller': ['Treking', 'Adventure', 'Long Trips', 'Short journeys'],
 'Age': array([33, 22, 19, 24, 24, 30, 23, 26, 18, 26, 19, 22, 21, 26, 23, 21, 19,
        31, 21, 21, 18, 20, 19, 19, 29, 23, 20, 19, 24, 19, 18, 26, 25, 23,
        34, 28, 24, 35, 19, 26, 20, 23, 47, 19, 26, 27, 24, 21, 32, 28, 21,
        32, 19, 21, 20, 28, 23, 24, 27, 18, 27, 25, 20, 23, 21, 19, 21, 24,
        31, 18, 25, 24, 24, 19, 22, 19, 18, 18, 20, 22, 24, 22, 29, 18, 22,
        21, 19, 23, 20, 25, 22, 20, 23, 23, 28, 18, 25, 18, 19, 22, 27, 18,
        22, 28, 26, 18, 20, 18, 22, 18, 31, 32, 20, 22, 20, 24, 25, 18, 23,
        21, 23, 22, 18, 22, 20, 20, 21, 31, 20, 21, 23, 27, 24, 27, 19, 28,
        21, 23, 32, 23, 25, 25, 31, 19, 19, 24, 20, 22, 35, 23, 25, 21, 36,
        22, 20, 18, 26, 27, 19, 24, 19, 21, 27, 19, 22, 18, 22, 24, 23, 25,
        20, 42, 24, 21, 19, 19, 26, 23, 24, 22, 25, 18, 20, 19, 18, 22, 21,
        28, 20, 21, 21, 19, 26, 19, 23, 19, 25, 21, 25, 30, 24, 18, 25, 19,
        18, 27, 18, 20, 26, 30, 19, 28, 22, 33, 28, 24, 24, 23, 20, 25, 37,
        28, 18, 23, 21, 24, 21, 18, 21, 23, 25, 27, 34, 24, 22, 22, 19, 18,
        24, 23, 30, 21, 20, 21, 21, 21, 27, 21, 25, 31, 27, 27, 27, 19, 34,
        20, 22, 20, 18, 21, 21, 28, 23, 21, 18, 28, 19, 27, 32, 23, 28, 28,
        32, 18, 25, 22, 18, 20, 27, 19, 28, 23, 20, 26, 19, 23, 33, 26, 19,
        21, 21, 21, 19, 29, 30, 24, 19, 25, 25, 24, 22, 21, 35, 26, 21, 20,
        26, 25, 21, 23, 18, 21, 23, 19, 25, 18, 18, 31, 27, 36, 30, 24, 20,
        20, 18, 18, 26, 46, 18, 21, 25, 21, 22, 18, 24, 28, 20, 26, 20, 34,
        22, 25, 20, 25, 20, 19, 20, 20, 22, 28, 29, 21, 24, 19, 20, 21, 20,
        26, 31, 22, 18, 29, 26, 24, 20, 30, 22, 31, 29, 26, 18, 28, 40, 18,
        19, 31, 19, 32, 21, 18, 20, 23, 23, 20, 22, 21, 23, 25, 21, 24, 28,
        29, 20, 18, 26, 28, 19, 29, 22, 19, 28, 21, 19, 20, 18, 21, 18, 38,
        26, 30, 23, 40, 18, 19, 20, 18, 19, 19, 27, 23, 18, 23, 27, 21, 19,
        18, 36, 18, 28, 18, 25, 31, 21, 21, 18, 22, 30, 18, 22, 27, 29, 20,
        21, 27, 27, 22, 32, 18, 20, 23, 20, 32, 28, 19, 24, 23, 22, 27, 18,
        26, 23, 34, 34, 28, 22, 20, 24, 23, 21, 22, 27, 23, 31, 22, 19, 22,
        21, 18, 18, 30, 33, 25, 22, 23, 19, 29, 22, 19, 18, 22, 24, 23, 21,
        21, 18, 28, 26, 21, 34, 20, 24, 19, 25, 24, 25, 24, 19, 32, 19, 21,
        32, 32, 19, 23, 21, 24, 24, 29, 21, 24, 19, 26, 18, 22, 26, 25, 20,
        18, 29, 28, 22, 26, 26, 30, 24, 25, 18, 25, 40, 34, 34, 30, 38, 23,
        25, 24, 18, 21, 19, 21, 19, 30, 19, 24, 24, 26, 24, 21, 42, 21, 23,
        27, 30, 19, 22, 21, 27, 22, 21, 21, 18, 26, 21, 33, 23, 24, 27, 18,
        26, 30, 20, 18, 36, 20, 34, 18, 26, 21, 22, 21, 19, 18, 35, 21, 18,
        20, 26, 21, 30, 20, 23, 27, 24, 33, 18, 27, 24, 20, 26, 23, 19, 23,
        33, 30, 22, 19, 18, 23, 18, 24, 27, 23, 28, 20, 29, 19, 19, 26, 23,
        21, 24, 30, 31, 23, 30, 26, 28, 20, 22, 21, 36, 29, 20, 23, 20, 21,
        18, 19, 27, 18, 23, 18, 19, 24, 27, 22, 27, 28, 18, 21, 18, 24, 18,
        26, 26, 20, 24, 26, 20, 19, 22, 25, 34, 31, 31, 25, 23, 31, 24, 24,
        23, 18, 30, 19, 23, 22, 20, 22, 26, 20, 25, 32, 21, 29, 20, 20, 28,
        25, 22, 19, 20, 20, 26, 22, 24, 38, 18, 18, 22, 22, 27, 24, 23, 18,
        23, 23, 31, 33, 19, 23, 24, 31, 25, 23, 19, 26, 23, 24, 27, 29, 18,
        19, 18, 24, 25, 26, 25, 21, 18, 28, 24, 23, 22, 30, 23, 23, 42, 26,
        30, 26])}

### Assigning random values to each subcategory of a category
Looping through the combined df, we will assign randomly generated value from each subcategory to the repsective category

In [9]:
# Looping through and assigning random values
for name, ops in combined.items():
    if name in ['Religion', 'Politics']:
        # Picking only 1 from the list
        df[name] = np.random.choice(ops, df.shape[0], p=p[name])
        
    elif name == 'Age':
        # Generating random ages based on a normal distribution
        df[name] = ops
    else:
        # Picking 3 from the list 
        try:
            df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3), p=p[name]))
        except:
            df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3)))
        
        df[name] = df[name].apply(lambda x: list(set(x[0].tolist())))

C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3), p=p[name]))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].apply(lambda x: list(set(x[0].tolist())))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = np.random.choice(ops, df.shape[0], p=p[name])
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3)))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].apply(lambda x: list(set(x[0].tolist())))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = np.random.choice(ops, df.shape[0], p=p[name])
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3), p=p[name]))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].apply(lambda x: list(set(x[0].tolist())))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3), p=p[name]))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].apply(lambda x: list(set(x[0].tolist())))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3)))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].apply(lambda x: list(set(x[0].tolist())))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = list(np.random.choice(ops, size=(df.shape[0],1,3)))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = df[name].apply(lambda x: list(set(x[0].tolist())))
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1128398756.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name] = ops

In [10]:
df

,Bios,Movies,Religion,Music,Politics,Social Media,Sports,Programming,Traveller,Age
0,Evil beer aficionado. Freelance introvert. Tv ...,"[Adventure, RomCom, Action]",Buddhist,"[Country, Pop, Romantic]",Progressive,"[LinkedIn, Facebook]","[Baseball, Chess, Basketball]","[C++, Java, C#]","[Short journeys, Long Trips, Adventure]",33
1,Passionate gamer. Evil internet aficionado. St...,"[Musical, Drama, Comedy]",Muslim,"[Jazz, Romantic, Rock]",Moderate,"[Youtube, Facebook, Pinterest]","[Cricket, Baseball, BadmintonFootball]","[C++, Swift]","[Short journeys, Long Trips, Adventure]",22
2,Social media guru. Tv expert. Amateur beer eva...,"[Adventure, RomCom, Action]",Christian,"[Romantic, EDM, HipHop]",Liberal,"[Youtube, Facebook]","[Cricket, BadmintonFootball, Chess]","[C++, Swift, Go]","[Short journeys, Long Trips, Adventure]",19
3,Reader. Incurable analyst. Proud pop culture e...,"[Adventure, Action, Thriller]",Other,"[Country, Romantic]",Liberal,"[Youtube, Facebook]","[Baseball, Cricket]","[Java, JavaScript]","[Long Trips, Adventure, Treking]",24
4,Typical gamer. Friend of animals everywhere. A...,"[Adventure, Drama, Action]",Christian,"[Jazz, Romantic, HipHop]",Liberal,"[Youtube, Facebook, SnapChat]","[Cricket, Hockey, Basketball]","[C++, Java, Swift]","[Adventure, Treking]",24
...,...,...,...,...,...,...,...,...,...,...
745,Social media fanatic. Typical coffee buff. Fre...,"[Drama, Adventure, Comedy]",Other,"[Classical, Romantic, HipHop]",Conservative,[Facebook],"[Baseball, Cricket, Chess]","[Python, Java, Go]","[Adventure, Treking]",23
746,Student. Reader. Bacon trailblazer. Explorer. ...,"[Drama, RomCom, Adventure]",Spiritual,"[Country, Pop, HipHop]",Conservative,"[Reddit, Facebook]","[Cricket, Baseball, Chess]","[JavaScript, Java, Go]","[Short journeys, Long Trips, Treking]",42
747,Reader. Tv lover. Beer nerd. Incurable interne...,"[Horror, Action, Thriller]",Hindu,"[Jazz, Country, Romantic]",Centrist,"[Youtube, Instagram]","[Cricket, Baseball, Hockey]","[Java, JavaScript]","[Short journeys, Long Trips, Adventure]",26
748,Amateur travel expert. Organizer. Alcohol fana...,"[Action, Adventure]",Christian,"[Pop, Romantic, HipHop]",Moderate,"[Youtube, Reddit, Facebook]","[Baseball, Other, BadmintonFootball]","[C++, Go]","[Short journeys, Long Trips, Treking]",30
749,Troublemaker. Food evangelist. Freelance inter...,"[Thriller, Comedy]",Atheist,"[Rock, Country, EDM]",Liberal,"[Youtube, Twitter]","[Baseball, Cricket, Chess]",[Java],"[Short journeys, Long Trips, Treking]",26

### Categorizing the religion and poilitics

In [11]:
df['Religion'] = pd.Categorical(df.Religion, ordered=True,
                                categories=['Catholic',
                                            'Christian',
                                            'Jewish',
                                            'Muslim',
                                            'Hindu',
                                            'Buddhist',
                                            'Spiritual',
                                            'Other',
                                            'Agnostic',
                                            'Atheist'])

df['Politics'] = pd.Categorical(df.Politics, ordered=True,
                                categories=['Liberal',
                                            'Progressive',
                                            'Centrist',
                                            'Moderate',
                                            'Conservative'])

C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1357384825.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Religion'] = pd.Categorical(df.Religion, ordered=True,
C:\Users\aksha\AppData\Local\Temp\ipykernel_18812\1357384825.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Politics'] = pd.Categorical(df.Politics, ordered=True,

In [12]:
df

,Bios,Movies,Religion,Music,Politics,Social Media,Sports,Programming,Traveller,Age
0,Evil beer aficionado. Freelance introvert. Tv ...,"[Adventure, RomCom, Action]",Buddhist,"[Country, Pop, Romantic]",Progressive,"[LinkedIn, Facebook]","[Baseball, Chess, Basketball]","[C++, Java, C#]","[Short journeys, Long Trips, Adventure]",33
1,Passionate gamer. Evil internet aficionado. St...,"[Musical, Drama, Comedy]",Muslim,"[Jazz, Romantic, Rock]",Moderate,"[Youtube, Facebook, Pinterest]","[Cricket, Baseball, BadmintonFootball]","[C++, Swift]","[Short journeys, Long Trips, Adventure]",22
2,Social media guru. Tv expert. Amateur beer eva...,"[Adventure, RomCom, Action]",Christian,"[Romantic, EDM, HipHop]",Liberal,"[Youtube, Facebook]","[Cricket, BadmintonFootball, Chess]","[C++, Swift, Go]","[Short journeys, Long Trips, Adventure]",19
3,Reader. Incurable analyst. Proud pop culture e...,"[Adventure, Action, Thriller]",Other,"[Country, Romantic]",Liberal,"[Youtube, Facebook]","[Baseball, Cricket]","[Java, JavaScript]","[Long Trips, Adventure, Treking]",24
4,Typical gamer. Friend of animals everywhere. A...,"[Adventure, Drama, Action]",Christian,"[Jazz, Romantic, HipHop]",Liberal,"[Youtube, Facebook, SnapChat]","[Cricket, Hockey, Basketball]","[C++, Java, Swift]","[Adventure, Treking]",24
...,...,...,...,...,...,...,...,...,...,...
745,Social media fanatic. Typical coffee buff. Fre...,"[Drama, Adventure, Comedy]",Other,"[Classical, Romantic, HipHop]",Conservative,[Facebook],"[Baseball, Cricket, Chess]","[Python, Java, Go]","[Adventure, Treking]",23
746,Student. Reader. Bacon trailblazer. Explorer. ...,"[Drama, RomCom, Adventure]",Spiritual,"[Country, Pop, HipHop]",Conservative,"[Reddit, Facebook]","[Cricket, Baseball, Chess]","[JavaScript, Java, Go]","[Short journeys, Long Trips, Treking]",42
747,Reader. Tv lover. Beer nerd. Incurable interne...,"[Horror, Action, Thriller]",Hindu,"[Jazz, Country, Romantic]",Centrist,"[Youtube, Instagram]","[Cricket, Baseball, Hockey]","[Java, JavaScript]","[Short journeys, Long Trips, Adventure]",26
748,Amateur travel expert. Organizer. Alcohol fana...,"[Action, Adventure]",Christian,"[Pop, Romantic, HipHop]",Moderate,"[Youtube, Reddit, Facebook]","[Baseball, Other, BadmintonFootball]","[C++, Go]","[Short journeys, Long Trips, Treking]",30
749,Troublemaker. Food evangelist. Freelance inter...,"[Thriller, Comedy]",Atheist,"[Rock, Country, EDM]",Liberal,"[Youtube, Twitter]","[Baseball, Cricket, Chess]",[Java],"[Short journeys, Long Trips, Treking]",26

### Saving and exporting the pickle file

In [13]:
with open("refined_profiles.pkl",'wb') as fp:
    pickle.dump(df, fp)