## Starting of Project

### Generating Fake Bio data

#### The first thing we do is import all the necessary libraries for us to run our web-scraper. We will be explaining the exceptional library packages for BeautifulSoup to run properly such as:

##### ♦requests allows us to access the webpage that we need to scrape.
##### ♦time will be needed in order to wait between webpage refreshes.
##### ♦tqdm is only needed as a loading bar for our sake.
##### ♦bs4 is needed in order to use BeautifulSoup.

In [2]:
import requests
import pandas as pd
import random
import time
import re #regex
import numpy as np
import _pickle as pickle
from tqdm import tqdm_notebook as tqdm
from bs4 import BeautifulSoup as bs

In [3]:
## Using beautiful soup to scrape data
# Randomizing the refresh rate
seq = [i/10 for i in range(8,18)]

# Creating a list of bios
biolist = []

# Gathering bios by looping and refreshing the web page
for _ in tqdm(range(1000)):
    
    # Refreshing the page
    page = requests.get("https://www.fakepersongenerator.com/user-biography-generator")
    soup = bs(page.content)
    
    try:
        # Getting the bios
        bios = soup.find('div', class_='row no-margin for-sign').find_all('p')

        # Adding to a list of the bios
        biolist.extend([re.findall('"([^"]*)"', i.text) for i in bios])
    except:
        pass
    
    # Sleeping 
    time.sleep(random.choice(seq))
    
# Creating a DF from the bio list
bio_df = pd.DataFrame(biolist, columns=['Bios'])

C:\Users\aksha\AppData\Local\Temp/ipykernel_11748/1936148274.py:9: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for _ in tqdm(range(1000)):

  0%|          | 0/1000 [00:00<?, ?it/s]

In [4]:
bio_df

                                                   Bios
0     Typical communicator. Subtly charming web advo...
1     Introvert. Friendly beer guru. Bacon fanatic. ...
2     Friend of animals everywhere. Passionate zombi...
3     Webaholic. Pop culture ninja. Wannabe organize...
4     Zombie buff. Troublemaker. Social media ninja....
...                                                 ...
8290  Wannabe analyst. General food enthusiast. Musi...
8291  Friendly pop cultureaholic. Analyst. Gamer. Am...
8292  Alcohol nerd. Award-winning music fan. Profess...
8293  Organizer. Introvert. Twitter junkie. Certifie...
8294  Unable to type with boxing gloves on. Devoted ...

[8295 rows x 1 columns]

#### Now, we will generate interests with a range from 0-9 depicting the interest level. The numbers represent the specific interest in the category.

In [10]:
# Using random library of python, we will generate a range from 0 to 9.

# We have set a list of common interests which will be asked by th user on the time of profile creation

interests_list = [
    'Movies',
    'TV',
    'Religion',
    'Music',
    'Sports',
    'Travelling',
    'Foodie',
    'Books',
    'Politics',
    'Finance',
    'Coding',
]

# Now creating a datafame of these inputs
interest_df = pd.DataFrame(columns = interests_list)

# Filling in Data
for i in interest_df.columns:
    
    # Range of numbers to represent different labels in each category
    interest_df[i] = np.random.randint(0,10, bio_df.shape[0])
    
    # Logic: The numbers represent a specific choice within the categories
    # So the number 1 preferred artist/song/album under the Music, your one favorite movie, etc.
    
# Joining the two dataframes
final_df = bio_df.join(interest_df)
final_df

,Bios,Movies,TV,Religion,Music,Sports,Travelling,Foodie,Books,Politics,Finance,Coding
0,Typical communicator. Subtly charming web advo...,0,6,4,2,2,2,5,2,3,5,5
1,Introvert. Friendly beer guru. Bacon fanatic. ...,0,3,5,5,7,3,7,5,4,2,0
2,Friend of animals everywhere. Passionate zombi...,2,5,6,4,3,0,3,1,8,7,8
3,Webaholic. Pop culture ninja. Wannabe organize...,4,2,9,6,9,5,0,5,1,5,2
4,Zombie buff. Troublemaker. Social media ninja....,3,0,9,6,7,1,0,2,3,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...
8290,Wannabe analyst. General food enthusiast. Musi...,1,2,1,1,1,5,6,2,7,2,9
8291,Friendly pop cultureaholic. Analyst. Gamer. Am...,1,4,8,2,8,5,5,3,1,5,1
8292,Alcohol nerd. Award-winning music fan. Profess...,2,6,3,0,0,2,7,1,1,9,0
8293,Organizer. Introvert. Twitter junkie. Certifie...,1,8,2,2,9,6,1,8,7,0,8
8294,Unable to type with boxing gloves on. Devoted ...,0,7,4,3,4,7,2,7,3,0,4

In [11]:
# Making a pickle file of the final dataframe 
# Exporting the complete DF
with open("profile_data.pkl", "wb") as fp:
    pickle.dump(final_df, fp)